language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge

install: travis_retry composer install --no-interaction --no-progress --optimize-autoloader

script: vendor/bin/phpspec run -v
